# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "Sitio"
  url = "sitio"
  weight = 10

[[main]]
  name = "Agoras"
  url = "evento"
  weight = 20

[[main]]
  name = "Tarantelas"
  url = "publicacion"
  weight = 30

[[main]]
  name = "Blog"
  url = "post"
  weight = 40

[[main]]
  name = "Equipo"
  url = "equipo"
  weight = 50

[[main]]
  name = "Contacto"
  url = "contacto"
  weight = 60
